### ISSUE TITLE
Encode ssh usernames for git as base62

### ISSUE THREAD

**Issue by phlmn** [flipdot/waboorrt#12]

**Comment by soerface** [comment]
Idea: rC3 usernames should be independent from accounts on our side. Users should be able to login via rC3, but create unique usernames in our system. By default we will use the rC3 username if it matches `[a-z0-9][a-z0-9-]*[a-z0-9]`. If it does not match, ask the user for an alternative username, and check uniqueness.

**Comment by soerface** [comment]
#17
